version: '3.4'

services:


  sourcingsqldb:
    image: mcr.microsoft.com/mssql/server


  esourcing.order:
    image: ${DOCKER_REGISTRY-}esourcingorder
    build:
      context: .
      dockerfile: ESourcing.Order/Dockerfile

  esourcing.apigateway:
    image: ${DOCKER_REGISTRY-}esourcingapigateway
    build:
      context: .
      dockerfile: ESourcing.APIGateway/Dockerfile

