version: '3.4'

services:



  sourcingsqldb:
    container_name: sourcingsqldb
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Copypaste123!!"
      ACCEPT_EULA: "Y"

 

  esourcing.order:
    container_name: esourcingorder
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=sourcingsqldb;Database=OrderDB;User Id=sa;Password=Copypaste123!!"
    depends_on:
      - sourcingsqldb
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/
    ports:
      - "8002:80"

  esourcing.apigateway:
    container_name: esourcingapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - esourcing.order
    ports:
      - "5000:80"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      - ${HOME}/.aspnet/https:/root/.aspnet/https/


