version: '3.4'

services:
  esourcing.apigateway:
    image: esourcingapigateway:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ESourcing.APIGateway"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_esourcing.apigateway$
    volumes:
      - C:\Users\ASUS\Desktop\OrjinalYedekler\SonHali\v1.3\ESourcing-master\ESourcing.APIGateway:/app
      - C:\Users\ASUS\Desktop\OrjinalYedekler\SonHali\v1.3\ESourcing-master:/src
      - C:\Users\ASUS\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_esourcing.apigateway$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_esourcing.apigateway$ \"/src/../../../../ESourcing-master/ESourcing.APIGateway/bin/Debug/net5.0/ESourcing.APIGateway.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  esourcing.order:
    image: esourcingorder:dev
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ESourcing.Order"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_esourcing.order$
    volumes:
      - C:\Users\ASUS\Desktop\OrjinalYedekler\SonHali\v1.3\ESourcing-master\ESourcing.Order:/app
      - C:\Users\ASUS\Desktop\OrjinalYedekler\SonHali\v1.3\ESourcing-master:/src
      - C:\Users\ASUS\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_esourcing.order$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_esourcing.order$ \"/src/../../../../ESourcing-master/ESourcing.Order/bin/Debug/net5.0/ESourcing.Order.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
