// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ordering.Infrastructure.Data;

namespace Ordering.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220205092037_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Ordering.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Order", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 3,
                            CreatedOn = new DateTime(2022, 2, 5, 12, 20, 37, 78, DateTimeKind.Local).AddTicks(8521),
                            CustomerName = "Can Güler",
                            Price = 17m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 5,
                            CreatedOn = new DateTime(2022, 1, 26, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2274),
                            CustomerName = "Mehmet Güler",
                            Price = 55m,
                            Status = 50,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            CreatedOn = new DateTime(2021, 12, 17, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2493),
                            CustomerName = "Ahmet Güler",
                            Price = 60m,
                            Status = 30,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CreatedOn = new DateTime(2022, 1, 26, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2505),
                            CustomerName = "Feyza Güler",
                            Price = 90m,
                            Status = 40,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 8,
                            CreatedOn = new DateTime(2022, 1, 31, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2509),
                            CustomerName = "Enise Güler",
                            Price = 70m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 7,
                            CreatedOn = new DateTime(2022, 1, 27, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2520),
                            CustomerName = "Adem Güler",
                            Price = 50m,
                            Status = 20,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 6,
                            CreatedOn = new DateTime(2021, 12, 2, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2524),
                            CustomerName = "Şimşek Güler",
                            Price = 220m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 5,
                            CreatedOn = new DateTime(2021, 11, 9, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2528),
                            CustomerName = "Abdullah Güler",
                            Price = 87m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 21,
                            CreatedOn = new DateTime(2022, 1, 25, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2531),
                            CustomerName = "Nurullah Güler",
                            Price = 65m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 14,
                            CreatedOn = new DateTime(2022, 1, 29, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2537),
                            CustomerName = "Enes Güler",
                            Price = 65m,
                            Status = 10,
                            StoreName = "Shopi"
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 2,
                            CreatedOn = new DateTime(2022, 1, 26, 12, 20, 37, 82, DateTimeKind.Local).AddTicks(2540),
                            CustomerName = "Emel Güler",
                            Price = 87m,
                            Status = 10,
                            StoreName = "Shopi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
